# Generated by Django 5.2 on 2025-04-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='news/videos/')),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
